<template>
  <div class="mx-auto max-w-3xl p-2 text-left">
    <p class="mb-2">
      Images of this NFT collection are dynamically generated by the smart
      contract on the Ethereum blockchain, using the world first vector-based
      on-chain font.
    </p>
    <ProviderView assetProvider="alphabet" :count="4" network="mainnet" />
    <Mint
      :network="network"
      :tokenGated="true"
      :tokenAddress="tokenAddress"
      :tokenGateAddress="tokenGateAddress"
      :limit="1"
      :xrestricted="'On-Chain Splatter or Bitcoin Art'"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useRoute } from "vue-router";
import Mint from "@/components/Mint.vue";
import ProviderView from "@/components/ProviderView.vue";
import { addresses } from "@/utils/addresses";

export default defineComponent({
  components: {
    ProviderView,
    Mint,
  },
  setup() {
    const route = useRoute();
    const network =
      typeof route.query.network == "string" ? route.query.network : "mainnet";
    const tokenAddress = addresses.alphabetToken[network];
    const tokenGateAddress = addresses.dynamic[network];
    console.log("*** chainId", network, tokenAddress);
    return {
      network,
      tokenAddress,
      tokenGateAddress,
    };
  },
});
</script>
